---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: "2024-11-18T13:27:06Z"
  name: wordpress
  namespace: jonas-was-here
  resourceVersion: "2953771"
  uid: 86262840-5d2d-414d-b1e5-22bfd026c443
spec:
  host: datasmurfan.cloud2.se
  port:
    targetPort: 8080
  to:
    kind: Service
    name: wordpress
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2024-11-18T13:27:06Z"
      status: "True"
      type: Admitted
    host: datasmurfan.cloud2.se
    routerCanonicalHostname: router-default.apps.cluster3.karoshi.se
    routerName: default
    wildcardPolicy: None
