---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-app
        image: "{{ .Values.commercialinvoice.image.repository }}:{{ default .Values.global.GLOBAL_VERSION .Values.commercialinvoice.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: wordpress-data
          mountPath: /opt/app-root/src
        - name: wp-config-file
          mountPath: /opt/app-root/src/wp-config.php
          subPath: wp-config.php
      volumes:
      - name: wp-config-file
        configMap:
          name: wp-config-php
          items:
          - key: wp-config.php
            path: wp-config.php
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-pvc

#example på om du vill låta jenkins refresha :

#    spec:
#      containers:
#        
#name: app
#       image: {{ .Values.commercialinvoice.image.repository }}:{{ default .Values.global.GLOBAL_VERSION .Values.commercialinvoice.image.tag }}
#        imagePullPolicy: Always
#
#        imagePullPolicy gör att om du startar om deploymenten så hämtas senaste docker hashen
#på den versionen du har deployat


